# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat2seqint <- function(mat) {
    .Call('EloRating2_mat2seqint', PACKAGE = 'EloRating2', mat)
}

steepint <- function(mat, nrand, Dij = TRUE) {
    .Call('EloRating2_steepint', PACKAGE = 'EloRating2', mat, nrand, Dij)
}

