# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fastelo <- function(WINNER, LOSER, ALLIDS, KVALS, STARTVALUES, NORMPROB = TRUE, ROUND = TRUE) {
    .Call('_EloRating_fastelo', PACKAGE = 'EloRating', WINNER, LOSER, ALLIDS, KVALS, STARTVALUES, NORMPROB, ROUND)
}

mat2seqint <- function(mat) {
    .Call('_EloRating_mat2seqint', PACKAGE = 'EloRating', mat)
}

steepint <- function(mat, nrand, Dij = TRUE) {
    .Call('_EloRating_steepint', PACKAGE = 'EloRating', mat, nrand, Dij)
}

